### ISSUE TITLE
您好，有配套后台吗？

### ISSUE THREAD

**Issue by mhkz** [aforwardz/KindlePusher#33]
我不知道推送的原理，所以想问有配套后台可供参考吗

**Comment by aforwardz** [comment]
@mhkz 不好意思，后台代码暂不提供：）
就是一个发邮件的逻辑

**Comment by aforwardz** [comment]
@mhkz 不可以的，亚马逊推送书籍也就是通过亚马逊邮箱来接收的，网盘没法发送到kindle邮箱，另外只有kindle邮箱里的白名单才可以推送上去，需要设置，还有书籍格式的问题
